[build]
  base = "dashboard"
  command = "npm run build"
  publish = ".next"

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (these will be set in Netlify UI)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=86400"

# Redirects for SPA routing
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

# API redirects for Supabase functions
[[redirects]]
  from = "/api/*"
  to = "https://liagltqpeilbswuqcahp.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer [SUPABASE_ANON_KEY]"}